import { StyleSheet } from "react-native-unistyles";

export const managedProviderSettingsStyles = StyleSheet.create((theme) => ({
  cardBody: {
    padding: theme.spacing[4],
    gap: theme.spacing[3],
  },
  dashedCard: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.lg,
    backgroundColor: theme.colors.surface1,
    padding: theme.spacing[6],
    alignItems: "center",
    gap: theme.spacing[2],
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: theme.colors.surface0,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: theme.spacing[1],
  },
  emptyTitle: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.medium,
    textAlign: "center",
  },
  emptyBody: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    textAlign: "center",
    maxWidth: 320,
    marginBottom: theme.spacing[2],
  },
  heroCardActive: {
    borderColor: theme.colors.palette.green[400],
    borderWidth: 1,
  },
  heroTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
    marginBottom: theme.spacing[1],
  },
  providerDotHero: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  heroLabel: {
    color: theme.colors.palette.green[400],
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  heroName: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.medium,
  },
  heroEndpoint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.sm,
    marginTop: theme.spacing[1],
  },
  heroKeyHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    marginTop: theme.spacing[2],
  },
  heroMetaHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    marginTop: theme.spacing[1],
  },
  providerMetaHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    marginTop: theme.spacing[1],
  },
  sectionHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  sectionHintEm: {
    color: theme.colors.foreground,
    fontWeight: theme.fontWeight.medium,
  },
  endpointRow: {
    gap: theme.spacing[2],
    alignSelf: "stretch",
    width: "100%",
  },
  fieldLabel: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  textInput: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface1,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[2],
  },
  errorHint: {
    color: theme.colors.destructive,
    fontSize: theme.fontSize.xs,
  },
  errorBlock: {
    gap: theme.spacing[2],
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing[3],
  },
  statusBadge: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.palette.green[400],
  },
  statusText: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    flexShrink: 1,
  },
  githubButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
    backgroundColor: "#24292e",
    paddingVertical: theme.spacing[3],
    paddingHorizontal: theme.spacing[4],
    alignSelf: "stretch",
    width: "100%",
  },
  githubButtonText: {
    color: theme.colors.palette.white,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  disabledButton: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  balanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  balanceLabel: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  balanceValue: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.medium,
  },
  routeSummaryGrid: {
    gap: theme.spacing[3],
  },
  routeSummaryCard: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface0,
    padding: theme.spacing[3],
    gap: theme.spacing[2],
  },
  routeSummaryCardMuted: {
    opacity: 0.8,
  },
  routeSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing[2],
  },
  routeSummaryTitle: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  routeSummaryBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: 2,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
    overflow: "hidden",
  },
  routeSummaryBadgeCloud: {
    backgroundColor: theme.colors.surface1,
    color: theme.colors.accent,
  },
  routeSummaryBadgeCustom: {
    backgroundColor: theme.colors.surface1,
    color: theme.colors.foregroundMuted,
  },
  routeSummaryProviderName: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  routeSummaryProviderHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  routeSummaryMetricsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing[2],
  },
  routeMetricCard: {
    flexGrow: 1,
    minWidth: 120,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface1,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[2],
    gap: theme.spacing[1],
  },
  routeMetricLabel: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  routeMetricValue: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  routeMetricSubvalue: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  infoBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: 2,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
    overflow: "hidden",
  },
  infoBadgeNeutral: {
    backgroundColor: theme.colors.surface1,
    color: theme.colors.foregroundMuted,
  },
  infoBadgeSuccess: {
    backgroundColor: theme.colors.surface1,
    color: theme.colors.palette.green[400],
  },
  infoBadgeWarning: {
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    color: "#b45309",
  },
  infoBadgeDanger: {
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    color: theme.colors.destructive,
  },
  infoBadgeAccent: {
    backgroundColor: theme.colors.surface1,
    color: theme.colors.accent,
  },
  usageMeterBlock: {
    gap: theme.spacing[1],
    marginTop: theme.spacing[1],
  },
  usageMeterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing[2],
  },
  usageMeterLabel: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  usageMeterValue: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  usageMeterTrack: {
    width: "100%",
    height: 6,
    borderRadius: 999,
    backgroundColor: theme.colors.surface2,
    overflow: "hidden",
  },
  usageMeterFillBase: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: theme.colors.accent,
  },
  usageMeterFillWarning: {
    backgroundColor: "#d97706",
  },
  usageMeterFillDanger: {
    backgroundColor: theme.colors.destructive,
  },
  usageWindowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing[2],
    marginTop: theme.spacing[1],
  },
  usageWindowPill: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 999,
    backgroundColor: theme.colors.surface1,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: 2,
  },
  usageWindowPillText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  routeInsightText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  configPreviewBlock: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface1,
    padding: theme.spacing[3],
  },
  usageHint: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
  },
  formTitle: {
    color: theme.colors.foreground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  groupPickerBlock: {
    gap: theme.spacing[2],
    alignSelf: "stretch",
  },
  groupComboWrap: {
    alignSelf: "stretch",
  },
  createKeyBlock: {
    gap: theme.spacing[2],
    marginTop: theme.spacing[2],
    paddingTop: theme.spacing[3],
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  keysSubsection: {
    marginTop: theme.spacing[3],
    paddingTop: theme.spacing[3],
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    gap: theme.spacing[2],
  },
  keyMatchBadge: {
    color: theme.colors.accent,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
    marginTop: theme.spacing[1],
  },
  editKeyGroupRow: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[2],
    marginBottom: theme.spacing[2],
    backgroundColor: theme.colors.surface0,
    gap: theme.spacing[1],
  },
  editKeyGroupRowSelected: {
    borderColor: theme.colors.accent,
    backgroundColor: "rgba(59,130,246,0.08)",
  },
  keyRowList: {
    gap: theme.spacing[2],
  },
  keyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    backgroundColor: theme.colors.surface0,
  },
  primaryButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.accent,
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[3],
  },
  primaryButtonText: {
    color: theme.colors.accentForeground,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  useKeyButtonUsed: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface2,
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[3],
  },
  useKeyButtonUsedText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface1,
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[3],
  },
  secondaryButtonText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  providerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  providerDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  providerDotActive: {
    backgroundColor: theme.colors.palette.green[400],
  },
  providerDotIdle: {
    backgroundColor: theme.colors.border,
  },
  providerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  keyActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  activeProviderText: {
    color: theme.colors.palette.green[400],
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  removeButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing[2],
    paddingHorizontal: theme.spacing[1],
  },
  removeButtonText: {
    color: theme.colors.destructive,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
  },
  formBody: {
    gap: theme.spacing[3],
  },
  formActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: theme.spacing[2],
  },
  addProviderButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface1,
    paddingVertical: theme.spacing[3],
  },
  addProviderButtonText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  tabBar: {
    alignSelf: "stretch",
  },
  routeHeroStack: {
    gap: theme.spacing[3],
  },
  scopeActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  scopeBadge: {
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.palette.green[400],
    marginRight: theme.spacing[1],
  },
  compactScopeButton: {
    paddingVertical: theme.spacing[1],
    paddingHorizontal: theme.spacing[2],
  },
  cloudShell: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: theme.spacing[4],
  },
  cloudShellCompact: {
    flexDirection: "column",
  },
  cloudMenuCard: {
    width: 220,
    alignSelf: "flex-start",
  },
  cloudMenuCardCompact: {
    width: "100%",
  },
  cloudMenuHeader: {
    paddingHorizontal: theme.spacing[4],
    paddingTop: theme.spacing[4],
    paddingBottom: theme.spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    gap: theme.spacing[1],
  },
  cloudMenuList: {
    padding: theme.spacing[2],
    gap: theme.spacing[1],
  },
  cloudMenuListCompact: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cloudMenuButton: {
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[3],
    backgroundColor: theme.colors.surface1,
  },
  cloudMenuButtonCompact: {
    minWidth: 120,
  },
  cloudMenuButtonActive: {
    backgroundColor: theme.colors.surface0,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cloudMenuButtonText: {
    color: theme.colors.foregroundMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
  },
  cloudMenuButtonTextActive: {
    color: theme.colors.foreground,
  },
  cloudContent: {
    flex: 1,
    minWidth: 0,
  },
}));
